import { Bouquet, Promotion, CustomFlower } from '@/types';

export const bouquets: Bouquet[] = [
  {
    id: '1',
    name: 'Весняний Рум\'янок',
    price: 1200,
    image: '/bouquets/spring-romance.jpg',
    category: 'romantic',
    description: 'Ніжний букет з рожевих троянд та білих піоній, ідеальний для романтичних моментів',
    flowers: ['Троянди', 'Півонії', 'Евкаліпт'],
    isNew: true,
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Сонячний Привіт',
    price: 950,
    originalPrice: 1200,
    image: '/bouquets/sunny-hello.jpg',
    category: 'bright',
    description: 'Яскравий букет соняшників та жовтих гербер для гарного настрою',
    flowers: ['Соняшники', 'Гербери', 'Хризантеми'],
    isSale: true,
    rating: 4.7,
  },
  {
    id: '3',
    name: 'Королівська Елегантність',
    price: 2500,
    image: '/bouquets/royal-elegance.jpg',
    category: 'premium',
    description: 'Розкішний букет з червоних троянд преміум класу',
    flowers: ['Червоні троянди', 'Орхідеї', 'Аспарагус'],
    rating: 5.0,
  },
  {
    id: '4',
    name: 'Лісова Казка',
    price: 1450,
    image: '/bouquets/forest-tale.jpg',
    category: 'rustic',
    description: 'Натуральний букет з польових квітів та зелені',
    flowers: ['Ромашки', 'Лаванда', 'Евкаліпт', 'Гіпсофіла'],
    isNew: true,
    rating: 4.8,
  },
  {
    id: '5',
    name: 'Ніжність Піоній',
    price: 1800,
    image: '/bouquets/peony-tenderness.jpg',
    category: 'romantic',
    description: 'Пишний букет з рожевих та білих піоній',
    flowers: ['Півонії', 'Ранункулюси', 'Евкаліпт'],
    rating: 4.9,
  },
  {
    id: '6',
    name: 'Тропічний Рай',
    price: 2200,
    originalPrice: 2800,
    image: '/bouquets/tropical-paradise.jpg',
    category: 'exotic',
    description: 'Екзотичний букет з стреліцій, протей та антуріумів',
    flowers: ['Стреліція', 'Протея', 'Антуріум'],
    isSale: true,
    rating: 4.6,
  },
  {
    id: '7',
    name: 'Білосніжна Мрія',
    price: 1650,
    image: '/bouquets/white-dream.jpg',
    category: 'wedding',
    description: 'Елегантний білий букет для весільних церемоній',
    flowers: ['Білі троянди', 'Лізіантус', 'Гіпсофіла'],
    rating: 5.0,
  },
  {
    id: '8',
    name: 'Осіння Палітра',
    price: 1350,
    image: '/bouquets/autumn-palette.jpg',
    category: 'seasonal',
    description: 'Теплі осінні відтінки в одному букеті',
    flowers: ['Хризантеми', 'Гербери', 'Троянди', 'Гілки'],
    rating: 4.7,
  },
];

export const promotions: Promotion[] = [
  {
    id: '1',
    title: 'Весняний Розпродаж',
    description: 'Знижка 20% на всі букети з півоніями',
    discount: 20,
    image: '/promotions/spring-sale.jpg',
    validUntil: new Date('2026-03-31'),
    code: 'SPRING20',
  },
  {
    id: '2',
    title: 'Безкоштовна Доставка',
    description: 'При замовленні від 2000 грн - доставка безкоштовна',
    discount: 0,
    image: '/promotions/free-delivery.jpg',
    validUntil: new Date('2026-12-31'),
    code: 'FREEDELIVERY',
  },
  {
    id: '3',
    title: 'День Закоханих',
    description: 'Спеціальна колекція романтичних букетів зі знижкою 15%',
    discount: 15,
    image: '/promotions/valentines.jpg',
    validUntil: new Date('2026-02-14'),
    code: 'LOVE15',
  },
];

export const customFlowers: CustomFlower[] = [
  { id: 'rose-red', name: 'Троянда червона', color: '#DC143C', price: 80, quantity: 0, image: '/flowers/rose-red.jpg' },
  { id: 'rose-pink', name: 'Троянда рожева', color: '#FFB6C1', price: 80, quantity: 0, image: '/flowers/rose-pink.jpg' },
  { id: 'rose-white', name: 'Троянда біла', color: '#FFFAF0', price: 85, quantity: 0, image: '/flowers/rose-white.jpg' },
  { id: 'peony-pink', name: 'Півонія рожева', color: '#FFB7C5', price: 150, quantity: 0, image: '/flowers/peony-pink.jpg' },
  { id: 'tulip-red', name: 'Тюльпан червоний', color: '#FF6347', price: 45, quantity: 0, image: '/flowers/tulip-red.jpg' },
  { id: 'tulip-yellow', name: 'Тюльпан жовтий', color: '#FFD700', price: 45, quantity: 0, image: '/flowers/tulip-yellow.jpg' },
  { id: 'lily-white', name: 'Лілія біла', color: '#FFFFF0', price: 120, quantity: 0, image: '/flowers/lily-white.jpg' },
  { id: 'sunflower', name: 'Соняшник', color: '#FFD700', price: 65, quantity: 0, image: '/flowers/sunflower.jpg' },
  { id: 'gerbera-orange', name: 'Гербера помаранчева', color: '#FF8C00', price: 55, quantity: 0, image: '/flowers/gerbera-orange.jpg' },
  { id: 'chrysanthemum', name: 'Хризантема', color: '#DDA0DD', price: 50, quantity: 0, image: '/flowers/chrysanthemum.jpg' },
  { id: 'eucalyptus', name: 'Евкаліпт', color: '#808080', price: 35, quantity: 0, image: '/flowers/eucalyptus.jpg' },
  { id: 'gypsophila', name: 'Гіпсофіла', color: '#FFFFFF', price: 40, quantity: 0, image: '/flowers/gypsophila.jpg' },
];

export const categories = [
  { id: 'all', name: 'Всі букети', icon: '💐' },
  { id: 'romantic', name: 'Романтичні', icon: '💕' },
  { id: 'bright', name: 'Яскраві', icon: '🌻' },
  { id: 'premium', name: 'Преміум', icon: '👑' },
  { id: 'rustic', name: 'Рустик', icon: '🌿' },
  { id: 'exotic', name: 'Екзотичні', icon: '🌺' },
  { id: 'wedding', name: 'Весільні', icon: '💒' },
  { id: 'seasonal', name: 'Сезонні', icon: '🍂' },
];
